name: Meme_Expansion

author: czssj_

description: A Slimefun4-Addon with some memes and some interesting things

main: me.czssj_.meme_expansion.Meme_Expansion

website: https://github.com/czszzh/Meme_Expansion

version: ${project.version}

api-version: 1.17

depend:
- Slimefun
- InfinityExpansion
- FluffyMachines

softdepend:
- RykenSlimefunCustomizer
- ExoticGarden
- Gastronomicon