name: Meme_Expansion

author: czssj_

description: A Slimefun4-Addon with some memes and some interesting things

main: me.czssj_.meme_expansion.Meme_Expansion
website: https://github.com/czszzh/Meme_Expansion

version: 1.0.9

api-version: 1.14

depend:
- Slimefun
- InfinityExpansion
- FluffyMachines

softdepend:
- RykenSlimefunCustomizer
- ExoticGarden
- Gastronomicon